server:
  port: 8182

spring:
  datasource:
    # 本地db文件的路径
    url: jdbc:sqlite:d:/cache-test/cache_manager.db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  file:
    path: d:/cache-test/log/manager-server

cache-manager-config:
  # 每隔多久应该生成一个新的密钥
  renew-frequency-sec: 600
  # 任务同步的最大天数，即只同步最近多少天的任务
  task-sync-max-day: 1
config:
  registry-urls:
  broker-urls: