server:
  port: 8182
  servlet:
    context-path: /manager

logging:
  file:
    path: d:/cache-test/log/manager-server

user-config:
  # 保留的旧密钥数
  old-key-count: 1
  # 预生成的密钥数
  future-key-count: 1
  # 每隔多久应该生成一个新的密钥
  renew-frequency-sec: 600