# 该配置文件各链路统一，若加应用服务器，只需要修改此文件即可
config:
  # 访问控制接口所需要的授权
  authorization: @authorization@
  # 本地缓存文件存储的目录
  file-cache-dir: @file-cache-dir@
  # 允许失效记录最大的存活时间
  record-expiry-sec: @record-expiry-sec@
  # 允许临时文件最大的存活时间
  temp-file-expiry-sec: @temp-file-expiry-sec@
  # 内容信息锁的超时
  content-info-lock-timeout-sec: @content-info-lock-timeout-sec@
  # 允许并发的最大任务数(主动模式)
  task-concurrent-max-count: @task-concurrent-max-count@
  # 任务重试的次数
  task-retry-count: @task-retry-count@

  # 定时器配置，首次时间格式为yyyy-MM-dd hh:mm:ss
  timers:
    # 清理长期不再使用的文件
    - name: FileCleaner
      first-time: @fileCleaner.first-time@
      interval-sec: @fileCleaner.interval-sec@
    # 清理长期不再使用的记录
    - name: RecordCleaner
      first-time: @recordCleaner.first-time@
      interval-sec: @recordCleaner.interval-sec@
    # 执行主动缓存
    - name: TaskExecuteTimer
      first-time: @taskExecuteTimer.first-time@
      interval-sec: @taskExecuteTimer.interval-sec@

  # 管理服务器配置，多个host使用“,”或“;”进行分隔
  manager-hosts: @manager-hosts@

  # 应用服务器配置
  app-servers:
    # EFB主应用
    - name: efb
      file-download-url: @efb.file-download-url@
      authorization: @efb.authorization@
    # EFB气象
    - name: weather
      file-download-url: @weather.file-download-url@
      authorization: @weather.authorization@
