# 该配置文件各链路统一，若加应用服务器，只需要修改此文件即可
config:
  # 本地缓存文件存储的目录
  file-cache-dir: d:/cache-test/cache/
  # 允许缓存目录使用磁盘空间的最大比例
  max-used-percent: 0.9
  # 下载请求的超时
  download-timeout-sec: 10
  temp-file-retain-sec: 3600
  temp-file-threshold-m: 40

  # 管理服务器配置，多个host使用“,”或“;”进行分隔
  manager-hosts: http://localhost:8182

  # 应用服务器配置
  app-servers:
    # EFB主应用
    - # noinspection SpringBootApplicationYaml
      name: app
      # noinspection SpringBootApplicationYaml
      file-download-url: http://localhost:8083/test1/getContentByFileId
      # noinspection SpringBootApplicationYaml
      authorization: 123456